key_save_file_base_path: "./KEYS"
default_remote: "samsung"
remotes:
  samsung:
    keys:
      power:
        code: "necx:0x70702"
      volume_up:
        code: "necx:0x70707"
      volume_down:
        code: "necx:0x7070b"
      mute:
        code: "necx:0x7070f"
      left:
        code: "necx:0x70765"
      right:
        code: "necx:0x70762"
      up:
        code: "necx:0x70760"
      down:
        code: "necx:0x70761"
      enter:
        code: "necx:0x70768"
      return:
        code: "necx:0x70758"
      exit:
        code: "necx:0x7072d"
      menu:
        code: "necx:0x7071a"
      source:
        code: "necx:0x70701"
      test_raw:
        key_path: "test_raw"
